spring.application.name=excelfile

#connection to postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/sandeshdb
spring.datasource.username=sandesh
spring.datasource.password=strongpassword


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#file configuration
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=10MB